### PR TITLE
Add new currency locale for India

### PR DESCRIPTION
**Pull request by cella**

### CODE REVIEW

**Comment by outerim** [comment]
This looks reasonable to me. @brettchalupa has done the most recent work with this Gem. He might be a good one to get some eyes on it also.

**Comment by outerim** [comment]
Should we use this opportunity to _not_ use rubygems but instead to make
this a private repo and bundle it like we do with most of the other private
gem dependencies?

**Comment by brettchalupa** [comment]
@outerim is there any reason to not keep it public and release new versions on RubyGems.org? If there are people outside of the org using this gem in their projects, I think it's a good think to keep updating and releasing versions of it.

**Comment by outerim** [comment]
Ah, I just remembered another reason it's public and that it probably needs to remain public... Dugway

**Pull request merged**
